-- MySQL Script generated by MySQL Workbench
-- Thu Feb 17 08:49:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universidad` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(45) NOT NULL,
  `puerta` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo postal` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL,
  `nombre_marca` VARCHAR(45) NULL,
  `Provedor_id` INT NOT NULL,
  PRIMARY KEY (`idMarca`),
  INDEX `fk_Marca_Provedor1_idx` (`Provedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_Provedor1`
    FOREIGN KEY (`Provedor_id`)
    REFERENCES `mydb`.`Provedor` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gafas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacion` VARCHAR(45) NOT NULL,
  `montura` VARCHAR(45) NOT NULL,
  `color montura` VARCHAR(45) NOT NULL,
  `color cristales` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `Provedor_id` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gafas_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `mydb`.`Marca` (`idMarca`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fecha alta` DATETIME NULL,
  `cliente referencia` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `gafas_id` INT NOT NULL,
  `Clientes_id` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`gafas_id`, `Clientes_id`),
  INDEX `fk_gafas_has_Clientes_Clientes1_idx` (`Clientes_id` ASC) VISIBLE,
  INDEX `fk_gafas_has_Clientes_gafas_idx` (`gafas_id` ASC) VISIBLE,
  INDEX `fk_Ventas_Empleados1_idx` (`Empleados_idEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_has_Clientes_gafas`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `mydb`.`gafas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gafas_has_Clientes_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleados` INT NOT NULL,
  `nombre_empleado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `gafas_id` INT NOT NULL,
  `Clientes_id` INT NOT NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`gafas_id`, `Clientes_id`),
  INDEX `fk_gafas_has_Clientes_Clientes1_idx` (`Clientes_id` ASC) VISIBLE,
  INDEX `fk_gafas_has_Clientes_gafas_idx` (`gafas_id` ASC) VISIBLE,
  INDEX `fk_Ventas_Empleados1_idx` (`Empleados_idEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_has_Clientes_gafas`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `mydb`.`gafas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gafas_has_Clientes_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ventas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
