db.restaurants.find()
db.restaurants.find({}, {"name":1, "borough":1, "cuisine":1})
db.restaurants.find({}, {"name":1, "borough":1, "cuisine":1, "_id":0})
db.restaurants.find({}, {"name":1, "borough":1, "address" : {"zipcode":1}, "_id":0})
db.restaurants.find({}, {"name":1, "borough": "Bronx", "_id":0})
db.restaurants.find({}, {"name":1, "borough": "Bronx", "_id":0}).limit(5).skip(5)
db.restaurants.find({}, {"score": >90, "name": 1, "_id":0})
db.restaurants.find({"grades.score":{$gt:90}})
db.restaurants.find({"grades.score":{$gt:80}, "grades.score":{$lt:100}})
db.restaurants.find({"address.coord":{$lt:-95.754168}})
db.restaurants.find($and:[{"cuisine":{$ne:"American"}, "grades.score":{$gt:90}, "address.coord":{$lt:-65.754168}}])
db.restaurants.find({"cuisine":{$ne:"American"}, "grades.score":{$gt:90}, "address.coord":{$lt:-65.754168}})
db.restaurants.find({"cuisine":{$ne:"American"}, "grades.grade" : "A", "borough":{$ne:"Brooklyn"}}).sort({"cuisine":1})
db.restaurants.find({"name": /^Wil/}, {"_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"name": /ces$/}, {"_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"name": /Reg/}, {"_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find( {"borough": "Bronx"}, {$or: [ {"cuisine":"American"}, {"cuisine":"Chinese"}]})
db.restaurants.find({$or: [ {"borough":"Staten Island"}, {"borough":"Queens"}, {"borough":"Bronx"}, {"borough":"Brooklyn"}]}, {"_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({$nor: [ {"borough":"Staten Island"}, {"borough":"Queens"}, {"borough":"Bronx"}, {"borough":"Brooklyn"}]}, {"_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({"grades.score":{$lt:10}}, {"_id":1, "name":1, "borough":1, "cuisine":1})
db.restaurants.find({$and: [{"name": /Seafood/},{$nor : {cuisine: {$in: ["American ", "Chinese"]}}, {"name": /^Wil/}}]}, {"name":1, "borough":1, "cuisine":1}) 
