USE tienda;
SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio * 1.125 FROM producto;
SELECT nombre AS "nombre de producto", precio AS "euros", (precio * 1.125) AS "dolares" FROM producto;
SELECT UPPER(nombre), UPPER(precio) FROM producto;
SELECT LOWER(nombre), LOWER(precio) FROM producto;
SELECT nombre, SUBSTRING(nombre,1,2) FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio,0) FROM producto;
SELECT codigo FROM producto;
SELECT DISTINCT codigo FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante WHERE codigo > 3 and codigo < 6;
SELECT nombre, precio FROM producto ORDER BY precio ASC  LIMIT 1;
USE universidad;
SELECT apellido1, apellido2, nombre FROM persona ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT apellido1, apellido2, nombre FROM persona  WHERE telefono IS NULL;
SELECT  nombre FROM persona WHERE LEFT(fecha_nacimiento, 4) = 1999;
SELECT nombre, apellido1, apellido2 FROM persona WHERE tipo = "profesor" AND telefono IS NULL  AND RIGHT (nif, 1) = "k";
SELECT * FROM asignatura WHERE cuatrimestre = "1" AND  id_grado = '7' AND curso = "3";
SELECT persona.nombre, apellido1, apellido2, departamento.nombre FROM persona JOIN departamento ON persona.id = departamento.id WHERE persona.tipo = "profesor";
SELECT nif, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM persona JOIN curso_escolar ON persona.id = curso_escolar.id WHERE nif = "26902806M";
SET @id = (SELECT id FROM grado WHERE grado.nombre = 'Grado en Ingeniería Informática (Plan 2015)'); SELECT departamento.nombre FROM departamento WHERE departamento.id = @id;
SET @id = (SELECT id FROM curso_escolar WHERE anyo_inicio = "2018" AND anyo_fin = "2019"); SELECT * FROM alumno_se_matricula_asignatura WHERE alumno_se_matricula_asignatura.id_curso_escolar = @id;
SELECT  persona.nombre, apellido1, apellido2, departamento.nombre FROM persona LEFT JOIN departamento ON persona.id = departamento.id WHERE tipo = "profesor" ORDER BY departamento.nombre ASC, apellido1 ASC, persona.nombre ASC;
SELECT  persona.nombre, apellido1, apellido2, departamento.nombre FROM persona LEFT JOIN departamento ON persona.id = departamento.id WHERE tipo = "profesor" AND departamento.nombre IS NULL ORDER BY apellido1 ASC, persona.nombre ASC;
SELECT nombre FROM departamento RIGHT JOIN profesor ON departamento.id = profesor.id_profesor WHERE profesor.id_departamento IS NULL;
SELECT  persona.nombre, apellido1, apellido2 FROM persona LEFT JOIN profesor ON persona.id = profesor.id_profesor LEFT JOIN departamento ON persona.id = departamento.id WHERE tipo = "profesor" AND departamento.id IS NULL;
SELECT id, nombre FROM asignatura WHERE id_profesor IS NULL;
SELECT departamento.nombre FROM departamento LEFT JOIN asignatura ON departamento.id = asignatura.id_profesor LEFT JOIN curso_escolar ON asignatura.curso = curso_escolar.id WHERE asignatura.curso IS NULL AND curso_escolar.id IS NULL;
SELECT COUNT(*) FROM persona WHERE tipo = "alumno";
SELECT COUNT(*) FROM persona WHERE tipo = "alumno" AND LEFT(fecha_nacimiento, 4) = 1999;
SELECT departamento.nombre, persona.nombre FROM departamento JOIN profesor ON departamento.id = profesor.id_departamento JOIN persona ON profesor.id_profesor = persona.id WHERE tipo = "profesor" ORDER BY persona.nombre ASC;
SELECT grado.nombre, COUNT(asignatura.id_grado) FROM grado LEFT JOIN asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre, asignatura.id_grado
