-- MySQL Script generated by MySQL Workbench
-- Mon Feb 14 16:37:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Provedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(45) NOT NULL,
  `puerta` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `codigo postal` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gafas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacion` VARCHAR(45) NOT NULL,
  `montura` VARCHAR(45) NOT NULL,
  `color montura` VARCHAR(45) NOT NULL,
  `color cristales` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `Provedor_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fecha alta` DATETIME NULL,
  `cliente referencia` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `Clientes_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Clientes` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `idVentas` INT NOT NULL AUTO_INCREMENT,
  `nombre vendedor` VARCHAR(45) NOT NULL,
  `fecha venta` DATETIME NOT NULL,
  `Ventascol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVentas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `idEmpleados` INT NOT NULL,
  `nombre_empleado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes_compra_gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes_compra_gafas` (
  `Clientes_id` INT NOT NULL,
  `gafas_id` INT NOT NULL,
  `nombre vendedor` VARCHAR(45) NULL,
  `fecha venta` DATETIME NULL,
  `Empleados_idEmpleados` INT NOT NULL,
  PRIMARY KEY (`Clientes_id`, `gafas_id`, `Empleados_idEmpleados`),
  INDEX `fk_Clientes_has_gafas_gafas1_idx` (`gafas_id` ASC) VISIBLE,
  INDEX `fk_Clientes_has_gafas_Clientes1_idx` (`Clientes_id` ASC) VISIBLE,
  INDEX `fk_Clientes_compra_gafas_Empleados1_idx` (`Empleados_idEmpleados` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_gafas_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_gafas_gafas1`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `mydb`.`gafas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_compra_gafas_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleados`)
    REFERENCES `mydb`.`Empleados` (`idEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marca` (
  `idMarca` INT NOT NULL,
  `nombre_marca` VARCHAR(45) NULL,
  `gafas_id` INT NOT NULL,
  `Provedor_id` INT NOT NULL,
  PRIMARY KEY (`idMarca`, `gafas_id`, `Provedor_id`),
  INDEX `fk_Marca_gafas1_idx` (`gafas_id` ASC) VISIBLE,
  INDEX `fk_Marca_Provedor1_idx` (`Provedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_Marca_gafas1`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `mydb`.`gafas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Marca_Provedor1`
    FOREIGN KEY (`Provedor_id`)
    REFERENCES `mydb`.`Provedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
