-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 15:30:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;





-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `codigo postal` INT NULL,
  `telefono` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`provincias` (
  `id_prov` INT NOT NULL,
  `nombre_prov` VARCHAR(45) NULL,
  PRIMARY KEY (`id_prov`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`localidades` (
  `id_local` INT NOT NULL,
  `provincias_id_prov` INT NOT NULL,
  PRIMARY KEY (`id_local`, `provincias_id_prov`),
  INDEX `fk_localidades_provincias1_idx` (`provincias_id_prov` ASC) VISIBLE,
  CONSTRAINT `fk_localidades_provincias1`
    FOREIGN KEY (`provincias_id_prov`)
    REFERENCES `mydb`.`provincias` (`id_prov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizzerias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizzerias` (
  `id` INT NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `codigo postal` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ID_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ID_pedidos` (
  `idID_pedidos` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  `ID_producto` INT NOT NULL,
  `pizzas_id` INT NOT NULL,
  `bebidas_idbebidas` INT NOT NULL,
  PRIMARY KEY (`idID_pedidos`, `pizzas_id`, `bebidas_idbebidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedidos` (
  `id` INT NOT NULL,
  `fecha hora` DATETIME NULL,
  `domicilio` TINYINT NULL,
  `cantidad` INT NULL,
  `precio` VARCHAR(45) NULL,
  `Pizzerias_id` INT NOT NULL,
  `Clientes_id` INT NULL,
  `Clientes_id1` INT NOT NULL,
  `ID_pedidos_idID_pedidos` INT NOT NULL,
  PRIMARY KEY (`id`, `Pizzerias_id`, `Clientes_id1`, `ID_pedidos_idID_pedidos`),
  INDEX `fk_Pedidos_Pizzerias1_idx` (`Pizzerias_id` ASC) VISIBLE,
  INDEX `fk_Pedidos_Clientes1_idx` (`Clientes_id1` ASC) VISIBLE,
  INDEX `fk_Pedidos_ID_pedidos1_idx` (`ID_pedidos_idID_pedidos` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Pizzerias1`
    FOREIGN KEY (`Pizzerias_id`)
    REFERENCES `mydb`.`Pizzerias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Clientes1`
    FOREIGN KEY (`Clientes_id1`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_ID_pedidos1`
    FOREIGN KEY (`ID_pedidos_idID_pedidos`)
    REFERENCES `mydb`.`ID_pedidos` (`idID_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizzas` (
  `id` INT NOT NULL,
  `nombre_pizza` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `precio` INT NULL,
  `ID_pedidos_idID_pedidos` INT NOT NULL,
  `ID_pedidos_pizzas_id` INT NOT NULL,
  `ID_pedidos_bebidas_idbebidas` INT NOT NULL,
  PRIMARY KEY (`id`, `ID_pedidos_idID_pedidos`, `ID_pedidos_pizzas_id`, `ID_pedidos_bebidas_idbebidas`),
  INDEX `fk_pizzas_ID_pedidos1_idx` (`ID_pedidos_idID_pedidos` ASC, `ID_pedidos_pizzas_id` ASC, `ID_pedidos_bebidas_idbebidas` ASC) VISIBLE,
  CONSTRAINT `fk_pizzas_ID_pedidos1`
    FOREIGN KEY (`ID_pedidos_idID_pedidos` , `ID_pedidos_pizzas_id` , `ID_pedidos_bebidas_idbebidas`)
    REFERENCES `mydb`.`ID_pedidos` (`idID_pedidos` , `pizzas_id` , `bebidas_idbebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Pizzas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pizzas_id`),
  INDEX `fk_categorias_Pizzas1_idx` (`Pizzas_id` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_Pizzas1`
    FOREIGN KEY (`Pizzas_id`)
    REFERENCES `mydb`.`pizzas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `cargo` VARCHAR(45) NULL,
  `Pizzerias_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Pizzerias_id`),
  INDEX `fk_Empleados_Pizzerias1_idx` (`Pizzerias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Pizzerias1`
    FOREIGN KEY (`Pizzerias_id`)
    REFERENCES `mydb`.`Pizzerias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Repartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Repartos` (
  `id` INT NOT NULL,
  `nombre repartidor` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes_has_provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes_has_provincias` (
  `Clientes_id` INT NOT NULL,
  `provincias_id_prov` INT NOT NULL,
  PRIMARY KEY (`Clientes_id`, `provincias_id_prov`),
  INDEX `fk_Clientes_has_provincias_provincias1_idx` (`provincias_id_prov` ASC) VISIBLE,
  INDEX `fk_Clientes_has_provincias_Clientes1_idx` (`Clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_provincias_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `mydb`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_provincias_provincias1`
    FOREIGN KEY (`provincias_id_prov`)
    REFERENCES `mydb`.`provincias` (`id_prov`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hamburguesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hamburguesas` (
  `idhamburguesas` INT NOT NULL,
  `Pedidos_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `ID_pedidos_idID_pedidos` INT NOT NULL,
  `ID_pedidos_pizzas_id` INT NOT NULL,
  `ID_pedidos_bebidas_idbebidas` INT NOT NULL,
  PRIMARY KEY (`idhamburguesas`, `ID_pedidos_idID_pedidos`, `ID_pedidos_pizzas_id`, `ID_pedidos_bebidas_idbebidas`),
  INDEX `fk_hamburguesas_ID_pedidos1_idx` (`ID_pedidos_idID_pedidos` ASC, `ID_pedidos_pizzas_id` ASC, `ID_pedidos_bebidas_idbebidas` ASC) VISIBLE,
  CONSTRAINT `fk_hamburguesas_ID_pedidos1`
    FOREIGN KEY (`ID_pedidos_idID_pedidos` , `ID_pedidos_pizzas_id` , `ID_pedidos_bebidas_idbebidas`)
    REFERENCES `mydb`.`ID_pedidos` (`idID_pedidos` , `pizzas_id` , `bebidas_idbebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebidas` (
  `idbebidas` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `ID_pedidos_idID_pedidos` INT NOT NULL,
  `ID_pedidos_pizzas_id` INT NOT NULL,
  `ID_pedidos_bebidas_idbebidas` INT NOT NULL,
  PRIMARY KEY (`idbebidas`, `ID_pedidos_idID_pedidos`, `ID_pedidos_pizzas_id`, `ID_pedidos_bebidas_idbebidas`),
  INDEX `fk_bebidas_ID_pedidos1_idx` (`ID_pedidos_idID_pedidos` ASC, `ID_pedidos_pizzas_id` ASC, `ID_pedidos_bebidas_idbebidas` ASC) VISIBLE,
  CONSTRAINT `fk_bebidas_ID_pedidos1`
    FOREIGN KEY (`ID_pedidos_idID_pedidos` , `ID_pedidos_pizzas_id` , `ID_pedidos_bebidas_idbebidas`)
    REFERENCES `mydb`.`ID_pedidos` (`idID_pedidos` , `pizzas_id` , `bebidas_idbebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleados_has_Repartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleados_has_Repartos` (
  `Empleados_id` INT NOT NULL,
  `Empleados_Pizzerias_id` INT NOT NULL,
  `Repartos_id` INT NOT NULL,
  PRIMARY KEY (`Empleados_id`, `Empleados_Pizzerias_id`, `Repartos_id`),
  INDEX `fk_Empleados_has_Repartos_Repartos1_idx` (`Repartos_id` ASC) VISIBLE,
  INDEX `fk_Empleados_has_Repartos_Empleados1_idx` (`Empleados_id` ASC, `Empleados_Pizzerias_id` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Repartos_Empleados1`
    FOREIGN KEY (`Empleados_id` , `Empleados_Pizzerias_id`)
    REFERENCES `mydb`.`Empleados` (`id` , `Pizzerias_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_has_Repartos_Repartos1`
    FOREIGN KEY (`Repartos_id`)
    REFERENCES `mydb`.`Repartos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
